version: '3.8'

services:
  dp:
    image: ghcr.io/1ndistinct/dp
    command: python -m dp api
    depends_on:
      - dbsetup
    volumes:
      - ./dp:/app/dp
    ports:
      - 8000:8000
    env_file:
      - .env

  dbsetup:
    image: ghcr.io/1ndistinct/dp
    command: python -m dp db upgrade
    depends_on:
      - db
    volumes:
      - ./dp:/app/dp
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ec7a5f23655bfee156f12076d1a3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
  minio_data:
    driver: local
