services:
  dp: 
    image: ghcr.io/1ndistinct/dp
    command: python -m dp api
    depends_on:
      - dbsetup
    volumes:
      - ./dp:/app/dp
    ports: 
      - 8000:8000
    env_file:
      - .env
    
  dbsetup: 
    image: ghcr.io/1ndistinct/dp
    command: python -m dp db upgrade
    depends_on:
      - db
    volumes:
      - ./dp:/app/dp
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./pg_data:/var/lib/postgresql/data
